### PR TITLE
Lots of work on the handle bars adding styling

### PR DESCRIPTION
**Pull request by zaclark369**

### CODE REVIEW

**Review by DrDano — APPROVED** [review]

**Comment by DrDano** [comment]
Nice header, looks good. Go ahead and merge, I say!

**Comment by katieclauswell** [comment]
> Nice header, looks good. Go ahead and merge, I say!

lol had to doublecheck which repo I was working in! Your feedback is always appreciated Daniel :P

**Comment by katieclauswell** [comment]
@StaticCloud I'm good with merging this if it doesn't conflict with any of the frontend login stuff you worked on.

**Comment by zaclark369** [comment]
@StaticCloud Look good?

**Pull request merged**
